[build]
target = "./cfg/mips32.json"


[target.mips32]
rustflags = ["-C", "link-args=-Tld/mips32.ld"]
runner = "qemu-system-mipsel -no-reboot -M malta -m 256M -nographic -kernel"


[unstable]
mtime-on-use = true
build-std = ["core", "alloc"]